# Integración continua Travis CI

# Lenguaje de programación

language: python 3.5

# Sistema operativo destino a probar

os: linux

# Distribución del sistema operativo

dist: xenial

# Requerimiento de permisos en Linux

sudo: enabled

# Compiladores a emplear

compiler: 
#  - gcc
   - clang

# Tareas a realizar antes de instalacción

before_install:

# Actualizar

  - sudo apt-get -qq update

# Configurar Git si no lo está

  - if [ ! `git config --get user.email` ]; then `git config --global user.email 'user@example.com'`; fi
  - if [ ! `git config --get user.name` ]; then `git config --global user.name 'Travis CI'`; fi

# Instalar CMAKE
  - wget -qO - https://apt.kitware.com/keys/kitware-archive-latest.asc | sudo apt-key add -
  - sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ xenial main'
  - sudo apt-get update
  - sudo apt-get install cmake

# Instalar YARP

  - sudo sh -c 'echo "deb http://www.icub.org/ubuntu xenial contrib/science" > /etc/apt/sources.list.d/icub.list'
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 57A5ACB6110576A6
  - sudo apt-get update
  - sudo apt-get install yarp

# Instalar OpenCV

  - sudo apt-get install libopencv-dev

# Instalar dependencias
  - sudo apt-get install git-core cmake freeglut3-dev pkg-config build-essential libxmu-dev libxi-dev libusb-1.0-0-dev cython
  - git clone https://github.com/OpenKinect/libfreenect


# Tareas a ejecutar antes de nuestra prueba

before_script:
  - cd programs

# Compilamos

script:
  - cd ..

# En caso de compilación exitosa

after_success:

# Notificaciones por correo

notifications:
email: true
